### PR TITLE
Implement Provider.list_zones for dynamic zone config support

### PR DESCRIPTION
**Pull request by freym**
This PR adds the ability to dynamically build a list of all active zones.
Official documentation:
https://github.com/octodns/octodns?tab=readme-ov-file#dynamic-zone-config

### CODE REVIEW

**Comment by olofvndrhr** [comment]
@freym
I updated the PR to use the internal "make_absolute" function.
Let me know what you think.

I will test everything tomorrow and then merge it.

Best regards

**Comment by freym** [comment]
Looks good

**Comment by poupryc** [comment]
Hi @freym and @olofvndrhr,

Is this the intended behaviour of adding the `list_zones` method but not setting `SUPPORTS_DYNAMIC = False` to True?

https://github.com/olofvndrhr/octodns-netbox-dns/blob/8e168c4d88de25da1a68eff15d955968daa6b23a/src/octodns_netbox_dns/__init__.py#L17

**Comment by olofvndrhr** [comment]
@poupryc 
Oh, this was an oversight. Will fix it asap.
Thanks for the report.

**Pull request merged**
